# Snapshot of official MetaCubeX release, updated 2026-10-08.
files=geoip.metadb,geosite.dat,ASN.mmdb,BundleMRS.7z
geoip.metadb.url=https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.metadb
geoip.metadb.size=8414245
geoip.metadb.sha256=82e60a80bb2e624f84e1a319cedd52b2487662cf479aa3b0148a6404f8db0498
geosite.dat.url=https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
geosite.dat.size=4254934
geosite.dat.sha256=b697cf0728afa1757297d528a83b5c2270ec06652cee5b788353bc246d6b2cd3
ASN.mmdb.url=https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb
ASN.mmdb.size=12069758
ASN.mmdb.sha256=e16e2db7ed72adc4443e16d7e33a25120ca58bd8d0f2e902b49ac6c50c3f4815
BundleMRS.7z.url=https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/BundleMRS.7z
BundleMRS.7z.size=9244077
BundleMRS.7z.sha256=77fa2fc13f8d793acc0e3ce31cee821965db26697bd55755584e86d5124da759
